### ISSUE TITLE
Running RTMsim

### ISSUE THREAD

**Issue by duhd1993** [obertscheiderfhwn/RTMsim#1] opened 2022-10-16 00:33 UTC
I'm having trouble running the code
```
julia> include("rtmsim_GUI.jl")
WARNING: replacing module rtmsim.
ERROR: LoadError: UndefVarError: PriorityObservable not defined
Stacktrace:
 [1] include(fname::String)
   @ Base.MainInclude ./client.jl:476
 [2] top-level scope
   @ ~/Documents/RTMsim-1.0.1/rtmsim_GUI.jl:2
 [3] include(fname::String)
   @ Base.MainInclude ./client.jl:476
 [4] top-level scope
   @ REPL[8]:1
in expression starting at /Users/haodong/Documents/RTMsim-1.0.1/rtmsim.jl:24
in expression starting at /Users/haodong/Documents/RTMsim-1.0.1/rtmsim_GUI.jl:2
```
Could you take a look?

**Comment by obertscheiderfhwn** [comment] 2022-10-16 13:43
Just tried the following steps on a different computer than used for code development. Operating system is Windows 10 pro. I was wable to reproduce the error. Obviously, some changes were performed in the Makie and GLMakie packages.

One has to change Line 30 in rtmsim.jl to "    using Makie  #: PriorityObservable" since this function is no longer available. Packages Makie and GLMakie are used for data visualization. I verified the functionality with "include("rtmsim.jl")" and then the commands from the list:

```
    rtmsim.plot_mesh("meshfiles\\mesh_permeameter1_foursets.bdf",1) for plotting the mesh defined in the bdf-file
    rtmsim.plot_sets("meshfiles\\mesh_permeameter1_foursets.bdf") for plotting the sets specified in the bdf-file
    rtmsim.rtmsim_rev1(1,"meshfiles\\mesh_permeameter1_foursets.bdf",200, 101325,1.225,1.4,0.06, 1.35e5,1.00e5, 3e-3,0.7,3e-10,1,1,0,0, 3e-3,0.7,3e-10,1,1,0,0, 3e-3,0.7,3e-11,1,1,0,0, 3e-3,0.7,3e-11,1,1,0,0, 3e-3,0.7,3e-9,1,1,0,0, 1,0,0,0, 0,"results.jld2",0,0.01,16) for starting a simulation with one pressure inlet port (sets 2, 3 and 4 are not used and consequently the preform parameters are ignored; since set 1 is a pressure inlet, also the parameters for set 1 are ignored and the only relevant parameter for the specified set is the pressure difference between injection and initial cavity pressure)
    rtmsim.rtmsim_rev1(1,"meshfiles\\mesh_permeameter1_foursets.bdf",200, 101325,1.225,1.4,0.06, 1.35e5,1.00e5, 3e-3,0.7,3e-10,1,1,0,0, 3e-3,0.7,3e-10,1,1,0,0, 3e-3,0.7,3e-11,1,1,0,0, 3e-3,0.7,3e-11,1,1,0,0, 3e-3,0.7,3e-9,1,1,0,0, 1,2,2,2, 0,"results.jld2",0,0.01,16) for starting a simulation with different patches and race tracking
    rtmsim.rtmsim_rev1(1,"meshfiles\\mesh_permeameter1_foursets.bdf",200, 101325,1.225,1.4,0.06, 1.35e5,1.00e5, 3e-3,0.7,3e-10,1,1,0,0, 3e-3,0.7,3e-10,1,1,0,0, 3e-3,0.7,3e-11,1,1,0,0, 3e-3,0.7,3e-11,1,1,0,0, 3e-3,0.7,3e-9,1,1,0,0, 1,2,2,2, 1,"results.jld2",0,0.01,16) for continuing the previous simulation
    rtmsim.plot_mesh("meshfiles\\mesh_annulusfiller1.bdf",2) for the manual selection of inlet ports with left mouse button click while key p is pressed
    rtmsim.rtmsim_rev1(1,"meshfiles\\mesh_annulusfiller1.bdf",200, 0.35e5,1.205,1.4,0.06, 0.35e5,0.00e5, 3e-3,0.7,3e-10,1,1,0,0, 3e-3,0.7,3e-10,1,1,0,0, 3e-3,0.7,3e-10,1,1,0,0, 3e-3,0.7,3e-10,1,1,0,0, 3e-3,0.7,3e-10,1,1,0,0, 0,0,0,0, 0,"results.jld2",1,0.01,16) for starting only with the interactively selected inlet ports
    rtmsim.plot_results("results.jld2") for plotting the final filling and pressure contours
    rtmsim.plot_overview(-1,-1) for plotting the filling contours at four equidistant time instances
    rtmsim.plot_filling(-1,-1) for plotting the filling at different time instances selected with a slider bar
    rtmsim.start_rtmsim("inputfiles\\input.txt") for starting a simulation with the parameters specified in the text file input.txt
```

Furthermore I tested the GUI.

Two issues came up:
- The GUI has a button to close the GUI and the plot window. The function for closing the plot window (line 241 in rtmsim_GUI.jl; "    #GLMakie.destroy!(GLMakie.global_gl_screen())") is no longer working and is therefore commented out until another solution is available.
-  Another issue which came up while testing on two different computers. The run-time optimized version for calculating the numerical gradient gives different results on different computers (In the interactive mode it might happen that only one cell forms an inlet. Using the original version (i.e. calling dpdx,dpdy=numerical_gradient(1,ind,p_old,cellneighboursarray,cellcentertocellcenterx,cellcentertocellcentery) with method=1 as first variable) solves that. I will try to resolve that during the next days.

I will update the files rtmsim.jl and rtmsim_GUI.jl accordingly, but won't create a new release.

**Comment by duhd1993** [comment] 2022-10-16 13:51
I will give it a try once you update the code. I have two suggestions:
1. Could you use a file instead of instructions for managing dependencies. I'm not very familiar with Julia. Something like requirements.txt for Python
2. Could you specify and fix the package version you use so that this kind of mistake won't happen again?

**Comment by obertscheiderfhwn** [comment] 2022-10-16 17:53
Okay. There is something similar to the requirements.txt, which is a toml-file. I will try to figure out if this makes the installation process simpler=user friedly. But this might take some time.

I updated the code on Github. Please copy the rtmsim.jl and rmtsim_GUI.jl into the repository directory. Julia is very good for runtime performance but lacks from plotting capabilities for contour plots on triangular meshes. It will be my responsibility to check continuously for their functionalities. Alternatively, I suppose one has to limit the basic post-processing.functionalities.

**Comment by obertscheiderfhwn** [comment] 2022-10-23 11:56
New release created. Package management is still unchanged. Please let me know if installation is successful?

**Closed as completed** 2023-02-14 19:30 UTC
